import React from 'react'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import About from '@/components/About'
import Head from 'next/head'

function about() {
  return (
    <div className='bg-[rgb(202,180,180)]'>
      <Head>
        <title>Maestro Pizzini</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/pizza1.png" />
      </Head>
      <Navbar/>
      <About />
      <Footer/>
    </div>
  )
}

export default about
