import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Firstsection from '@/components/Firstsection'
import Secondsection from '@/components/Secondsection'
import Thirdsection from '@/components/Thirdsection'
import Fourthsection from '@/components/Fourthsection'
import Fifthsection from '@/components/Fifthsection'
import Sixsection from '@/components/Sixsection'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ backgroundImage: 'url(/img/bg.jpg)' }} className='h-full pb-16 bg-no-repeat bg-cover'><Navbar />
        <Firstsection />
      </div>
      <Secondsection />
      <Thirdsection />
      <Fourthsection />
      <Fifthsection />
      <Sixsection />
      <Footer />
    </>
  )
}
