import Menu from '@/components/Menu'
import React, { Component } from 'react'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import About from '@/components/About'
import Head from 'next/head'


export class menu extends Component {
    render() {
        return (
            <div>
                <Head>
                    <title>Maestro Pizzini</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/img/pizza1.png" />
                </Head>
                <div className='bg-[rgb(34,33,33)]'>
                    <Navbar />
                    <Menu />
                    <About/>
                </div>
                <Footer/>
            </div>
        )
    }
}

export default menu
